---
title: "kaggle"
author: "Sungcheol Kim"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
```

## Categorical Feature Encoding Challenge II

```{r cars}
dirname <- 'data_cat_maxAUC_0.78'
flist <- list.files(path=dirname, pattern='0.*.csv')
auclist <- as.numeric(gsub(".csv", "", flist))

train <- fread(paste0(dirname, '/', 'train.csv'))
y <- as.factor(train$target)
rho <- sum(y == 1)/length(y)

predictions <- matrix(nrow = 400000, ncol=length(flist))

i <- 1
for (f in flist) {
  tmp <- fread(paste0(dirname, '/', f))
  predictions[ ,i] <- tmp[[2]]
  i <- i + 1
}

dim(predictions)
```

```{r}
head(predictions)
```

```{r}
hist(predictions[, 1])
```

```{r}
library(summa)
ksumma <- summa::summa(predictions, "rank")
```

```{r}
hist(ksumma@estimated_rank)
```

```{r}
fde1 <- fdensemble(predictions[,1:8])
```

```{r}
fde1 <- predict_performance(fde1, auclist[1:8], rho, alpha = 1)
```

```{r}
plot_cor(fde1, class_flag='positive')
```

```{r}
hist(fde1@predictions[ ,4])
```

```{r}
submit <- data.table(id=seq(600000,999999), target=fde1@estimated_rank)
fwrite(submit, file='submission.csv')
```

```{r}
plot_cor(fde1, legend_flag=T)
```

```{r}
cor(fde1@rank_matrix)
```

## west nile virus prediction

```{r cars}
dirname <- 'data_west_nile_maxAUC_0.85'
flist <- list.files(path=dirname, pattern='0.*.csv')
auclist <- as.numeric(gsub(".csv", "", flist))

train <- fread(paste0(dirname, '/', 'train.csv'))
y <- as.factor(train$WnvPresent)
rho <- sum(y == 1)/length(y)

predictions <- matrix(nrow = 116293, ncol=length(flist))

i <- 1
for (f in flist) {
  tmp <- fread(paste0(dirname, '/', f))
  predictions[ ,i] <- tmp[[2]]
  i <- i + 1
}

dim(predictions)
```

```{r}
head(predictions)
```

```{r}
hist(predictions[, 1])
```

```{r}
library(summa)
ksumma <- summa::summa(predictions, "rank")
```

```{r}
plot.scores(ksumma@estimated_rank, as.factor(ksumma@estimated_label))
```

```{r}
fde1 <- fdensemble(predictions[,1:9])
```

```{r}
fde1 <- predict_performance(fde1, auclist[1:9], rho, alpha=1)
```

```{r}
idx <- order(fde1@estimated_rank)
plot(fde1@estimated_rank[idx])
lines(fde1@logit_matrix[idx,10], col='green')
lines(fde1@logit_matrix[idx,9], col='red')
lines(fde1@logit_matrix[idx,8], col='blue')
```

```{r}
plot.scores(fde1@estimated_rank, fde1@estimated_label)
```

```{r}
table(fde1@estimated_label)
```

```{r}
plot(fde1@estimated_rank, fde1@estimated_prob)
```

```{r}
rmax <- max(ksumma@estimated_rank)
rmin <- min(ksumma@estimated_rank)
submit <- data.table(Id=seq(1,116293), WnvPresent=(ksumma@estimated_rank - rmin)/(rmax-rmin))
fwrite(submit, file='submission.csv')
```

```{r}
submit <- data.table(Id=seq(1,116293), WnvPresent=fde1@estimated_prob)
fwrite(submit, file='submission.csv')
```

```{r}
plot_cor(fde1, class_flag='negative')
```

```{r}
cor(fde1@rank_matrix)
```

## Porto Seguro's Safe Driver Prediction

```{r}
dirname <- 'data_porto_maxGini_0.29'
flist <- list.files(path=dirname, pattern='0.*.csv')
auclist <- (as.numeric(gsub(".csv", "", flist)) + 1)/2

train <- fread(paste0(dirname, '/', 'train.csv'))
y <- as.factor(train$target)
rho <- sum(y == 1)/length(y)

predictions <- matrix(nrow = 892816, ncol=length(flist))

i <- 1
for (f in flist) {
  tmp <- fread(paste0(dirname, '/', f))
  predictions[ ,i] <- tmp[[2]]
  i <- i + 1
}

dim(predictions)
```

```{r}
head(predictions)
```

```{r}
hist(predictions[, 7])
```

```{r}
library(summa)
ksumma <- summa::summa(predictions, "rank")
```

```{r}
print(max(ksumma@estimated_rank))
print(min(ksumma@estimated_rank))
hist(ksumma@estimated_rank)
```

```{r}
fde1 <- fdensemble(predictions)
```

```{r}
fde1 <- predict_performance(fde1, auclist, rho, alpha=1)
```

```{r}
print(max(fde1@estimated_rank))
print(min(fde1@estimated_rank))
hist(fde1@estimated_rank)
```

```{r}
hist(fde1@predictions[ ,4])
```

```{r}
rmax <- max(ksumma@estimated_rank)
rmin <- min(ksumma@estimated_rank)
submit <- data.table(id=tmp$id, target=(ksumma@estimated_rank - rmin)/(rmax-rmin))
fwrite(submit, file='submission.csv')
```

```{r}
LILU <- function(x) {
  xmax <- max(x)
  xmin <- min(x)
  idx <- x >= 0
  y <- x
  y[idx] <- 0.5*y[idx]/xmax
  y[!idx] <- -0.5*y[!idx]/xmin
  return(y+0.5)
}

submit <- data.table(id=tmp$id, target=fde1@estimated_rank)
fwrite(submit, file='submission.csv')
```

```{r}
plot_cor(fde1, class_flag='negative')
```

```{r}
cor(fde1@rank_matrix)
```

## check r_summa


```{r}
library(summa)

data_binary <- create_predictions(3000, 30, 0.3, "rank")
str(data_binary)
```

```{r}
summ <- summa(data_binary$predictions, "rank")
```

```{r}
summ <- calculate_performance(summ, data_binary$actual_labels)
```

```{r}
summa_plot(summ)
```

