---
title: "Data_set_3 - Bank"
author: "Sungcheol Kim"
date: "12/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mlbench)
library(caret)
library(AppliedPredictiveModeling)
library(dplyr)

source('rprob.R')
```

## Bank data
```{r}
prepareData <- function(fname) {
  temp <- read.csv(fname, sep = ';')
  
  #dummies <- dummyVars(y ~ ., data = df)
  #ndf <- predict(dummies, newdata = df)
  
  return(temp)
}

df <- prepareData('bank.csv')

table(df$y)
rho = 521/(4000 + 521)
rho
```

```{r}
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                           classProbs = TRUE,
                           summaryFunction = twoClassSummary)

gbmGrid <-  expand.grid(interaction.depth = 4:7, 
                        n.trees = (1:6)*50, 
                        shrinkage = 0.1,
                        n.minobsinnode = 20)

#set.seed(998)
inTraining <- createDataPartition(df$y, p = .75, list = FALSE)
training <- df[ inTraining,]
testing  <- df[-inTraining,]
```

```{r}
gbmFit <- train.gbm(y ~ ., training, fitControl, gbmGrid)
svmFit <- train.svm(y ~ ., training, fitControl, 8)
rdaFit <- train.rda(y ~ ., training, fitControl, 8)
plsFit <- train.pls(y ~ ., training, fitControl, 8)
```

### check parameter fitting

```{r}
ggplot(gbmFit)
ggplot(svmFit)
ggplot(rdaFit)
ggplot(plsFit)
```

### Select best parameters

```{r, fig.width=4, fig.height=3}

pdf('Data3-ROC-svm.pdf', width = 6, height = 6)
roc.svm <- modelplot.roc(svmFit, testing, testing$y)
dev.off()

pdf('Data3-ROC-gbm.pdf', width = 6, height = 6)
roc.gbm <- modelplot.roc(gbmFit, testing, testing$y)
dev.off()

pdf('Data3-ROC-rda.pdf', width = 6, height = 6)
roc.rda <- modelplot.roc(rdaFit, testing, testing$y)
dev.off()

pdf('Data3-ROC-pls.pdf', width = 6, height = 6)
roc.pls <- modelplot.roc(plsFit, testing, testing$y)
dev.off()
```

## Calculate Rank

```{r}
a <- modelplot.rank(list(gbmFit, svmFit, rdaFit, plsFit), testing)
a
```

## Rank class probability

```{r}
rprob.gbm <- iterate.model('gbm', df, df$y, y~., 10, gbmFit$bestTune)
lambda.gbm <- fitFD(rprob.gbm, 'gbm 10 iter', df$y)
```

```{r}
rprob.svm <- iterate.model('svm', df, df$y, y~., 10, svmFit$bestTune)
lambda.svm <- fitFD(rprob.svm, 'svm 10 iter', df$y)
```

```{r}
rprob.rda <- iterate.model('rda', df, df$y, y~., 10, rdaFit$bestTune)
lambda.rda <- fitFD(rprob.rda, 'rda 10 iter', df$y)
```

```{r}
rprob.pls <- iterate.model('pls', df, df$y, y~., 10, plsFit$bestTune)
lambda.pls <- fitFD(rprob.pls, 'pls 10 iter', df$y)
```

## SUMMA+

```{r}
gbmFit$lambda <- lambda.gbm
svmFit$lambda <- lambda.svm
rdaFit$lambda <- lambda.rda
plsFit$lambda <- lambda.pls
```

```{r}
source('rprob.R')
summa.prob <- summaplus.predict(list(gbmFit, svmFit, rdaFit, plsFit), testing, testing$y)
```

```{r}
pdf('Data3-ROC-summa+.pdf', width=6, height=6)
summa.roc <- modelplot.roc(summa.prob, testing, testing$y, is.model=FALSE)
dev.off()
```