---
title: "Fitting lambda1, lambda2"
output: html_notebook
---

```{r}
source('rprob.R')
load('Abalone_20iter_v2.RData')
# rho = 839/(693 + 839)  for young

l.gbm <- fitFD(result, 'gbm', 0.5477)
l.svm <- fitFD(result, 'svm', 0.5477)
l.rda <- fitFD(result, 'rda', 0.5477)
l.pls <- fitFD(result, 'pls', 0.5477)
```

```{r}
load('Abalone_30iter_v2.RData')
# rho = 839/(693 + 839)  for young

l.gbm <- fitFD(result, 'gbm', 0.5477)
l.svm <- fitFD(result, 'svm', 0.5477)
l.rda <- fitFD(result, 'rda', 0.5477)
l.pls <- fitFD(result, 'pls', 0.5477)
```

```{r}
load('Abalone_40iter_v2.RData')
# rho = 839/(693 + 839) = 0.547  for young

l.gbm <- fitFD(result, 'gbm', 0.5477)
l.svm <- fitFD(result, 'svm', 0.5477)
l.rda <- fitFD(result, 'rda', 0.5477)
l.pls <- fitFD(result, 'pls', 0.5477)
```


```{r}
pdf('summa+_Abalone.pdf')
r = result$rank
f = l.gbm$l2*(l.gbm$rs - r) + l.svm$l2*(l.svm$rs - r) + l.rda$l2*(l.rda$rs - r) + l.pls$l2*(l.pls$rs - r)

H <- function(x) as.numeric(x>0)
find0 <- function(x) which.min(abs(x))

plot(r, f, type='l', xlab='Rank', ylab='SUMMA Score')
points(r, H(f), col='blue')

rFinal = find0(f)
abline(v=rFinal, col='gray')
text(rFinal, 0, sprintf('rank = %i', rFinal), adj=c(1,1))
dev.off()
```


```{r}
load('Sonar_10iter.RData')
# rho = 111/(111 + 97) = 0.533

l.gbm <- fitFD(result, 'gbm', 0.533)
l.svm <- fitFD(result, 'svm', 0.533)
l.rda <- fitFD(result, 'rda', 0.533)
l.pls <- fitFD(result, 'pls', 0.533)
```

```{r}
load('Sonar_20iter.RData')
# rho = 111/(111 + 97) = 0.533

l.gbm <- fitFD(result, 'gbm', 0.533)
l.svm <- fitFD(result, 'svm', 0.533)
l.rda <- fitFD(result, 'rda', 0.533)
l.pls <- fitFD(result, 'pls', 0.533)
```

```{r}
load('Sonar_30iter.RData')
# rho = 111/(111 + 97) = 0.533

l.gbm <- fitFD(result, 'gbm', 0.533)
l.svm <- fitFD(result, 'svm', 0.533)
l.rda <- fitFD(result, 'rda', 0.533)
l.pls <- fitFD(result, 'pls', 0.533)
```

```{r}
load('Sonar_40iter.RData')
# rho = 111/(111 + 97) = 0.533

l.gbm <- fitFD(result, 'gbm', 0.533)
l.svm <- fitFD(result, 'svm', 0.533)
l.rda <- fitFD(result, 'rda', 0.533)
l.pls <- fitFD(result, 'pls', 0.533)
```

```{r}
pdf('summa+_Sonar.pdf')
r = result$rank
f = l.gbm$l2*(l.gbm$rs - r) + l.svm$l2*(l.svm$rs - r) + l.rda$l2*(l.rda$rs - r) + l.pls$l2*(l.pls$rs - r)

H <- function(x) as.numeric(x>0)
find0 <- function(x) which.min(abs(x))

plot(r, f, type='l', xlab='Rank', ylab='SUMMA Score')
points(r, H(f), col='blue')

rFinal = find0(f)
abline(v=rFinal, col='gray')
text(rFinal, 0, sprintf('rank = %i', rFinal), adj=c(1,1))
dev.off()
```

