---
title: "UCI Sonar"
output: html_notebook
---

# ML training (Sonar)

## Preparations

```{r}
library(mlbench)
library(FDclassifieR)
```

```{r}
#set.seed(1024)
data(Sonar)
inTraining0 <- createDataPartition(Sonar$Class, p = .75, list = FALSE)
training <- Sonar[ inTraining0,]
testing  <- Sonar[-inTraining0,]
testingY <- as_label(Sonar[-inTraining0, ncol(Sonar)])
```

```{r}
t1 <- mtrainer(c('nnet', 'rda')) %>%
  train(Class~., training, update=F) %>%
  predict(newdata=testing)
```

```{r}
t1 <- t1 %>%
  addmodel.mtrainer(c('mlp', 'nb', 'rf', 'rpart', 'xgbTree', 'ctree', 'C5.0', 'gbm', 'bayesglm', 'earth', 'glm', 'avNNet', 'glmnet', 'simpls')) %>%
  train(Class~., training, update=F)
```

```{r}
t1 <- t1 %>%
  addmodel.mtrainer(c('svmLinear', 'svmRadial', 'pls', 'knn', 'earth', 'avNNet')) %>%
  train(Class~., training, update=F)
```

```{r}
plot(t1)
```

```{r}
t1 <- predict(t1, newdata=testing)
auclist <- apply(t1$predictions, 2, auc.rank, testingY)

fde1 <- fde(t1$predictions)
fde1 <- predict_performance(fde1, auclist, attr(testingY, 'rho'))
```

```{r}
plot_cor(fde1, legend_flag = T)
```

```{r}
fde1 <- fde(t1$predictions, testingY)
```

```{r}
plot_single(fde1, 'score')
```

```{r}
store.mtrainer(t1, 'sonar_m8_pre.RData')
saveRDS(testingY, 'sonar_m8_y.RData')
```

# Using caretEnsemble

```{r}
library(mlbench)
library(tictoc)
library('caret')
library("caretEnsemble")

data(Sonar)
inTraining0 <- createDataPartition(Sonar$Class, p = .75, list = FALSE)
training <- Sonar[ inTraining0,]
testing  <- Sonar[-inTraining0,]
#testingY <- as_label(Sonar[-inTraining0, ncol(Sonar)])

my_control <- trainControl(
  method="boot",
  number=10,
  savePredictions="final",
  classProbs=TRUE,
  index=createResample(training$Class, 10),
  summaryFunction=twoClassSummary
  )

seeds <- vector(mode = "list", length = 51)
for(i in 1:50) seeds[[i]] <- sample.int(1000, 22)
seeds[[51]] <- sample.int(1000, 1)
my_control2 <- trainControl(
  method = "repeatedcv", repeats = 5,
  savePredictions="final", 
  classProbs = TRUE, summaryFunction = twoClassSummary,
  search = "random", seeds = seeds)

tic()

model_list <- caretList(
  Class~., data=training,
  savePredictions="final",
  trControl=my_control2,
  methodList=c('nnet', 'rda', 'ctree', 'C5.0', 'gbm')
  )

toc()
```

```{r}
p <- predict(model_list, newdata=testing)
```

```{r}
library(FDclassifieR)
testingY <- as_label(Sonar[-inTraining0, ncol(Sonar)])
fde1 <- fde(p, testingY)
```

```{r}
plot_cor(fde1)
```

