---
title: "UCI - Ionosphere"
author: "Sungcheol Kim"
date: "12/19/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mlbench)
library(FDclassifieR)
```

## Prepare Data

```{r}
set.seed(1024)
data(Ionosphere)

Iono <- Ionosphere
Iono <- Iono[,-2]
Iono$V1 <- as.numeric(as.character(Iono$V1))

inTraining0 <- createDataPartition(Iono$Class, p = .75, list = FALSE)
training <- Iono[ inTraining0,]
testing  <- Iono[-inTraining0,]
testingY <- as_label(Iono[-inTraining0, ncol(Iono)])
```

```{r}
table(Iono[, ncol(Iono)])
```

```{r}
model_list <- c('nnet', 'rda', 'svmLinear', 'svmRadial', 'pls', 'knn', 'earth', 'avNNet', 'mlp', 'nb', 'rf', 'rpart', 'ctree', 'C5.0', 'gbm', 'bayesglm', 'glm', 'glmnet', 'simpls')
t1 <- mtrainer(model_list, dataInfo = 'Iono')
```

```{r}
t1 <- train(t1, Class~., training, update=T)
```

```{r}
plot(t1)
```


```{r}
t1 <- predict(t1, newdata=testing)
```

```{r}
#auclist <- apply(t1$predictions, 2, auc.rank, testingY)

fde1 <- fde(t1$predictions, testingY)
#fde1 <- predict_performance(fde1, auclist, attr(testingY, 'rho'))
```

```{r}
plot_cor(fde1, class_flag='positive')
```

```{r}
fde1 <- fde(t1$predictions, testingY)
```

```{r}
plot_single(fde1, 'score')
```

```{r}
store.mtrainer(t1, 'iono_m8_pre.RData')
saveRDS(testingY, 'iono_m8_y.RData')
```

```{r}
saveRDS(t1, 'iono_all.RData')
```

